### ISSUE TITLE
Build process documentation

### ISSUE THREAD

**Issue by kuanb** [conveyal/browsochrones-example#1]
I'd like to run this locally. I downloaded the repo and ran `npm install`. I note that `index.html` calls to a `build/` folder which appears to be a product of `lib/` and perhaps specifically `index.js`.

I assume you use Browserify on this ... Would be cool if there was light documentation on the steps? Maybe just me being unfamiliar with React + Browserify atm. 

`browserify lib/index.js -o build/index.js` returns a SyntaxError.

**Comment by kuanb** [comment]
```
SyntaxError: Unexpected token (4:7) while parsing /***/browsochrones-example/lib/index.js while parsing file: /***/browsochrones-example/lib/index.js
    at DestroyableTransform.end [as _flush] (/usr/local/Cellar/node/6.5.0/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.<anonymous> (/usr/local/Cellar/node/6.5.0/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/usr/local/Cellar/node/6.5.0/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/usr/local/Cellar/node/6.5.0/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
    at endWritable (/usr/local/Cellar/node/6.5.0/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (/usr/local/Cellar/node/6.5.0/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DestroyableTransform.onend (/usr/local/Cellar/node/6.5.0/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:495:10)
```

**Comment by kuanb** [comment]
Would be interested still but just realized this isn't something I can just run independently (noticed https://github.com/conveyal/browsochrones-example/blob/master/configurations/default/env.yml.tmp).

**Comment by kuanb** [comment]
Closing this - sorry. I spoke with Trevor. Thought this was something it was not.

I misread the description and thought it was somehow and on the fly isochrone creator… Or did something with client side tile generation.
